---
- hosts: all
  become: true
  tasks:
    - name: apt get update cache
      apt: update_cache=yes
    - name: install apt-transport-https
      apt: name=apt-transport-https state=latest update_cache=yes
    - name: apt upgrade
      apt: name='*' state=latest
    - name: apt docker io
      apt: name=docker.io state=latest update_cache=yes
    - name: enable service docker
      systemd:
        name: docker
        enabled: yes
        masked: no